### PR TITLE
fr-translation

### PR DESCRIPTION
**Pull request by BibichePython**

### CODE REVIEW

**Comment by BibichePython** [comment]
Hi Alex, 

a few month ago, I translated missions into french, but it seems they are still not merged : 

https://checkio.org/mission/network-attack/ 
https://checkio.org/mission/the-square-chest/ 
https://checkio.org/mission/friendly-number/ 

thanks for all ! 
Katia 

----- Mail original -----

De: "Alexander Lyabah" <notifications@github.com> 
À: "CheckiO-Missions/checkio-task-box-probability" <checkio-task-box-probability@noreply.github.com> 
Cc: "BibichePython" <bibiche.python@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 3 Mai 2016 18:14:42 
Objet: Re: [CheckiO-Missions/checkio-task-box-probability] fr-translation (#4) 



Merged #4 .

**Comment by Bryukh** [comment]
@oduvan

**Comment by oduvan** [comment]
Hi there.
I may miss them. Let me check.
BTW, we are working on JS version of CheckiO right now. Do you want to
participate in closed beta when it will be live?





On Tue, May 31, 2016 1:17 PM, Bryukhanov Valentin notifications@github.com wrote:
@oduvan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub , or mute the thread .



Alex CEO, CheckiO Inc.

CheckiO CheckiO is the game for coders. Improve your code with the help of our
community. checkio.org

Empire of Code Space strategy game where coding is your extra weapon empireofcode.com

Follow us

**Comment by oduvan** [comment]
All pull request have been merged. Thank you @BibichePython  for you contribution, and @Bryukh for tagging me

**Pull request merged**
