### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by DahliaSR**
@oduvan 
reviewed and confirmed - :shipit: 

closes CheckIO-to-German/Roadmap#38

### CODE REVIEW

**Comment by oduvan** [comment]
released

**Comment by DahliaSR** [comment]
> released

not yet, it says it shows "german" but it does show the english version...

image

**Comment by oduvan** [comment]
Oh I missed it.
Can you put files with translations into "info" folder?  





On Wed, Jun 28, 2017 8:56 PM, DahliaSR notifications@github.com  wrote:
released

not yet, it says it shows "german" but it does show the english version...



—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.



AlexCEO, CheckiO Inc.

CheckiO CheckIO - online game for Python and JavaScript coders checkio.org  

Alexander Lyabah – Medium Read writing from Alexander Lyabah on Medium.
Founder at @PlayCheckiO. Every day, Alexander Lyabah and thousands of other
voices read, write, and share important stories… medium.com  

Follow us

**Comment by DahliaSR** [comment]
what should the folder structure look like? 

info/de/...
or
info/translations/de/...

and where to put hints from now on?

**Comment by oduvan** [comment]
nothing is changed

screen shot 2017-06-29 at 8 17 45 am

you just need to put files from folder de into folder de/info

you see?

**Comment by DahliaSR** [comment]
Yes... NOW I see it... - :woman_facepalming:

**Comment by DahliaSR** [comment]
and here we go....

https://github.com/CheckiO-Missions/checkio-task-box-probability/pull/8

**Comment by oduvan** [comment]
> Yes... NOW I see it... - :woman_facepalming:

haha.. awesome smile.

Released.

**Pull request merged**
